version: '3'

services:

  gateway-service:
    build: ../gateway
    container_name: gateway-service
    ports:
      - '${GATE_WAY_PORT}:${GATE_WAY_PORT}'
    expose:
      - '${GATE_WAY_PORT}'

  front-end:
    build: ../frontend
    container_name: frontend
    ports:
      - '${FRONT_END_PORT}:80'
    expose:
      - '${FRONT_END_PORT}'


  alc-service-db:
    image: ${ALC_SERVICE_DB_IMAGE_NAME}
    container_name: ${ALC_SERVICE_DB_CONTAINER_NAME}
    volumes:
      - app-data:/var/lib/mysql
    ports:
      - "${ALC_SERVICE_DB_PORT}:${ALC_SERVICE_DB_PORT}"
    environment:
      - MYSQL_DATABASE=${ALC_SERVICE_DB_NAME}
      - MYSQL_USER=${ALC_SERVICE_DB_USER}
      - MYSQL_PASSWORD=${ALC_SERVICE_DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${ALC_SERVICE_DB_PASSWORD_ROOT}

  alc-service-back:
    build: ${ALC_SERVICE_PROJECT_PATH}
    container_name: ${ALC_SERVICE_CONTAINER_NAME}
    image: ${ALC_SERVICE_IMAGE_NAME}
    ports:
      - "${ALC_SERVICE_BACK_PORT}:${ALC_SERVICE_BACK_PORT}"
    environment:
      - ALC_SERVICE_DB_URL=jdbc:mysql://alc-service-db:3306/${ALC_SERVICE_DB_NAME}?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - ALC_SERVICE_DB_USER=${ALC_SERVICE_DB_USER}
      - ALC_SERVICE_DB_PASSWORD=${ALC_SERVICE_DB_PASSWORD}
    depends_on:
      - alc-service-db



volumes:
  app-data:

