version: '3'

services:
    
  zyn-service-db:
    image: ${ZYN_SERVICE_DB_IMAGE_NAME}
    container_name: ${ZYN_SERVICE_DB_CONTAINER_NAME}
    volumes:
      - app-data:/var/lib/mysql
    ports:
      - "${ZYN_SERVICE_DB_PORT}:${ZYN_SERVICE_DB_PORT}"
    environment:
      - MYSQL_DATABASE=${ZYN_SERVICE_DB_NAME}
      - MYSQL_USER=${ZYN_SERVICE_DB_USER}
      - MYSQL_PASSWORD=${ZYN_SERVICE_DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${ZYN_SERVICE_DB_PASSWORD_ROOT}

  zyn-service-back:
    build: ${ZYN_SERVICE_PROJECT_PATH}
    container_name: ${ZYN_SERVICE_CONTAINER_NAME}
    image: ${ZYN_SERVICE_IMAGE_NAME}
    ports:
      - "${ZYN_SERVICE_BACK_PORT}:${ZYN_SERVICE_BACK_PORT}"
    environment:
      - ZYN_SERVICE_DB_URL=jdbc:mysql://zyn-service-db:3306/${ZYN_SERVICE_DB_NAME}?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - ZYN_SERVICE_DB_USER=${ZYN_SERVICE_DB_USER}
      - ZYN_SERVICE_DB_PASSWORD=${ZYN_SERVICE_DB_PASSWORD}
    depends_on:
      - zyn-service-db



volumes:
  app-data:

